[project]
name = "pdf-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "googletrans==3.1.0a0",
    "pymupdf>=1.26.6",
    "requests>=2.31.0",
]
